netcdf MASTER_swfo-stis-ground-lut {
dimensions:
	event_counter = 672 ; 
	detectors = 6 ; 
	detector_coincidences = 14 ; 
	energy_bins = 48 ; 
	nonlut_adc_bins = 49 ; 
	range = 2 ; 
	scalar = 1 ; 
	channels_decimated = 4 ; 
	reaction_wheels = 4 ; 
	model_proton_energies_in_O = 8 ; 
	model_proton_energies_in_F = 6 ; 
	model_electron_energies_in_F = 5 ; 
	epam_ion_edge_energies = 9 ; 
	epam_electron_edge_energies = 5 ; 
	geant_energies = 240 ; 
	dim_char = 4 ; 
	dim_unit_vector = 3 ; 
variables:
	char channel_names (detectors, dim_char) ; 
		channel_names:long_name = "channel_names" ; 
		channel_names:comments = "Name of each channel (1,2 ,3 4, 5, 6)" ; 
		channel_names:units = "unitless" ; 
	char detector_names (detectors, dim_char) ; 
		detector_names:long_name = "detector_names" ; 
		detector_names:comments = "Name of each channel (O1, O2  O, F3, F4, F5)" ; 
		detector_names:units = "unitless" ; 
	char coincidence_names (detector_coincidences, dim_char) ; 
		coincidence_names:long_name = "coincidence_names" ; 
		coincidence_names:comments = "Name of each channel coincidence (O1, F1, O2, F2, O12, F12, O3, F3, O13, F13, O23, F23, O123, F123)" ; 
		coincidence_names:units = "unitless" ; 
	ubyte telescope_id_map (event_counter) ; 
		telescope_id_map:long_name = "telescope_id_map" ; 
		telescope_id_map:comments = "Indices mapping from L1a count rate histogram to telescope type (0 = O or proton; 1 = F or electron)" ; 
		telescope_id_map:units = "unitless" ; 
	ubyte fto_logic_id_map (event_counter) ; 
		fto_logic_id_map:long_name = "fto_logic_id_map" ; 
		fto_logic_id_map:comments = "Indices mapping from L1a count rate histogram to event types (1-7, corresponding to 1, 2, 12, 3, 13, 23, 123)" ; 
		fto_logic_id_map:units = "unitless" ; 
	double geometric_factor (detectors) ; 
		geometric_factor:long_name = "geometric_factor" ; 
		geometric_factor:comments = "Geometric factor for detector (O1, O2, O3, F1, F2, F3)" ; 
		geometric_factor:units = "cm^2 sr" ; 
	ubyte geometric_factor_coincidence_index (detector_coincidences) ; 
		geometric_factor_coincidence_index:long_name = "geometric_factor_coincidence_index" ; 
		geometric_factor_coincidence_index:comments = "Index of geometric_factors array to use for each detector coincidence" ; 
		geometric_factor_coincidence_index:units = "unitless" ; 
	long nonlut_ADC_bins (nonlut_adc_bins) ; 
		nonlut_ADC_bins:long_name = "nonlut_ADC_bins" ; 
		nonlut_ADC_bins:comments = "The ADC bins from the FPGA for the non-LUT mode, which is a pseudo-log compressed table to map the readout of the 13 most significant bits of the pulse height in each detector." ; 
		nonlut_ADC_bins:units = "ADC" ; 
	double efficiency (detector_coincidences, energy_bins) ; 
		efficiency:long_name = "efficiency" ; 
		efficiency:comments = "The efficiency of the detector, scales the geometric factor." ; 
		efficiency:units = "unitless" ; 
	double temperature_coefficient (detectors) ; 
		temperature_coefficient:long_name = "temperature_coefficient" ; 
		temperature_coefficient:comments = "Temperature scaling coefficient for energy" ; 
		temperature_coefficient:units = "unitless" ; 
	double energy_to_ADC_calibration (detectors) ; 
		energy_to_ADC_calibration:long_name = "energy_to_ADC_calibration" ; 
		energy_to_ADC_calibration:comments = "Energy (keV) per pulse height (ADC) measured for Americium-241 (59.5 keV) line in each detector (O1, O2, O3, F1, F2, F3)." ; 
		energy_to_ADC_calibration:units = "keV/ADC" ; 
	ubyte ADC_coincidence_multiplier (detector_coincidences) ; 
		ADC_coincidence_multiplier:long_name = "ADC_coincidence_multiplier" ; 
		ADC_coincidence_multiplier:comments = "Multiplier (1, 2, 4) that describes each coincidence." ; 
		ADC_coincidence_multiplier:units = "unitless" ; 
	ubyte energy_response_function (scalar) ; 
		energy_response_function:long_name = "energy_response_function" ; 
		energy_response_function:comments = "This bit indicates whether to use the cubic spline for determining particle energy (1) or a fixed dead layer offset (0)." ; 
		energy_response_function:units = "unitless" ; 
	double proton_O_dead_layer (scalar) ; 
		proton_O_dead_layer:long_name = "proton_O_dead_layer" ; 
		proton_O_dead_layer:comments = "Energy deposited in the dead layer by protons in the O detector" ; 
		proton_O_dead_layer:units = "keV" ; 
	double electron_F_dead_layer (scalar) ; 
		electron_F_dead_layer:long_name = "electron_F_dead_layer" ; 
		electron_F_dead_layer:comments = "Energy deposited in the dead layer by electrons in the F detector" ; 
		electron_F_dead_layer:units = "keV" ; 
	double proton_F_dead_layer (scalar) ; 
		proton_F_dead_layer:long_name = "proton_F_dead_layer" ; 
		proton_F_dead_layer:comments = "Energy deposited in the dead layer by protons in the F detector" ; 
		proton_F_dead_layer:units = "keV" ; 
	double modeled_proton_energy_loss_in_O (model_proton_energies_in_O) ; 
		modeled_proton_energy_loss_in_O:long_name = "modeled_proton_energy_loss_in_O" ; 
		modeled_proton_energy_loss_in_O:comments = "Simulated proton energy loss in O as a function of measured energy." ; 
		modeled_proton_energy_loss_in_O:units = "keV" ; 
	double modeled_proton_energy_measured_in_O (model_proton_energies_in_O) ; 
		modeled_proton_energy_measured_in_O:long_name = "modeled_proton_energy_measured_in_O" ; 
		modeled_proton_energy_measured_in_O:comments = "Simulated proton energy measured in O." ; 
		modeled_proton_energy_measured_in_O:units = "keV" ; 
	double modeled_proton_energy_loss_in_F (model_proton_energies_in_F) ; 
		modeled_proton_energy_loss_in_F:long_name = "modeled_proton_energy_loss_in_F" ; 
		modeled_proton_energy_loss_in_F:comments = "Simulated proton energy loss in F as a function of measured energy." ; 
		modeled_proton_energy_loss_in_F:units = "keV" ; 
	double modeled_proton_energy_measured_in_F (model_proton_energies_in_F) ; 
		modeled_proton_energy_measured_in_F:long_name = "modeled_proton_energy_measured_in_F" ; 
		modeled_proton_energy_measured_in_F:comments = "Simulated proton energy measured in F." ; 
		modeled_proton_energy_measured_in_F:units = "keV" ; 
	double modeled_electron_energy_loss_in_F (model_electron_energies_in_F) ; 
		modeled_electron_energy_loss_in_F:long_name = "modeled_electron_energy_loss_in_F" ; 
		modeled_electron_energy_loss_in_F:comments = "Simulated electron energy loss in F as a function of measured energy." ; 
		modeled_electron_energy_loss_in_F:units = "keV" ; 
	double modeled_electron_energy_measured_in_F (model_electron_energies_in_F) ; 
		modeled_electron_energy_measured_in_F:long_name = "modeled_electron_energy_measured_in_F" ; 
		modeled_electron_energy_measured_in_F:comments = "Simulated electron energy measured in F." ; 
		modeled_electron_energy_measured_in_F:units = "keV" ; 
	double dead_time (scalar) ; 
		dead_time:long_name = "dead_time" ; 
		dead_time:comments = "Dead time for each detector coincidence (O-1, O-2, O-12, O-3, O-13, O-23, O-123, F-1, F-2, F-12, F-3, F-13, F-23, F-123)." ; 
		dead_time:units = "s" ; 
	double dead_time_correction_criteria (range) ; 
		dead_time_correction_criteria:long_name = "dead_time_correction_criteria" ; 
		dead_time_correction_criteria:comments = "Range of (non-paralyzable) dead time scaling factors [1 / (1 - count_rate_#s*deadtime_s)] for applying the dead time criterion to merge small and large pixels to get the high-dynamic range flux. At big pixel dead time scaling factor below the first element, use the big pixel and ignore the small pixel. At the dead time scaling factors above the second element, use the small pixel and ignore the big pixel. Between, a weighting factor for big pixel is calculated as a linear function of deadtime criterion between 0 and 1." ; 
		dead_time_correction_criteria:units = "unitless" ; 
	double poisson_statistics_criteria (range) ; 
		poisson_statistics_criteria:long_name = "poisson_statistics_criteria" ; 
		poisson_statistics_criteria:comments = "The count range for applying the Poisson criterion to merge small and large pixels to get the high-dynamic range flux. At counts below the first element, the small pixel is ignored (poor counting statistics) and the big pixel is used. At counts above the second element, the big pixel is ignored and the small pixel is used. Between the two, a power law is used to calculate a weighting factor between 0 and 1." ; 
		poisson_statistics_criteria:units = "# counts" ; 
	double poisson_statistics_power_coefficient (scalar) ; 
		poisson_statistics_power_coefficient:long_name = "poisson_statistics_power_coefficient" ; 
		poisson_statistics_power_coefficient:comments = "The coefficient for the power law used for the Poisson criterion to merge small and large pixels to get the high-dynamic range flux. " ; 
		poisson_statistics_power_coefficient:units = "unitless" ; 
	double noise_sigma_threshold (detectors) ; 
		noise_sigma_threshold:long_name = "noise_sigma_threshold" ; 
		noise_sigma_threshold:comments = "If the standard deviation of the differenced noise in a channel exceeds this value, set a bit in the quality flag." ; 
		noise_sigma_threshold:units = "counts" ; 
	double count_rate_threshold (detectors) ; 
		count_rate_threshold:long_name = "count_rate_threshold" ; 
		count_rate_threshold:comments = "If the count rate for each detector exceeds this value, the data quality flags is set." ; 
		count_rate_threshold:units = "counts per second" ; 
	double dap_temperature_range (range) ; 
		dap_temperature_range:long_name = "dap_temperature_range" ; 
		dap_temperature_range:comments = "If STIS DAP temperature (temp_dap) lies outside this range, the data quality flag is set." ; 
		dap_temperature_range:units = "degrees Celsius" ; 
	double sensor_1_temperature_range (range) ; 
		sensor_1_temperature_range:long_name = "sensor_1_temperature_range" ; 
		sensor_1_temperature_range:comments = "If STIS S1 temperature (temp_sensor1) lies outside this range, the data quality flag is set." ; 
		sensor_1_temperature_range:units = "degrees Celsius" ; 
	double sensor_2_temperature_range (range) ; 
		sensor_2_temperature_range:long_name = "sensor_2_temperature_range" ; 
		sensor_2_temperature_range:comments = "If STIS S2 temperature (temp_sensor2) lies outside this range, the data quality flag is set." ; 
		sensor_2_temperature_range:units = "degrees Celsius" ; 
	double reaction_wheel_speed_threshold (reaction_wheels) ; 
		reaction_wheel_speed_threshold:long_name = "reaction_wheel_speed_threshold" ; 
		reaction_wheel_speed_threshold:comments = "If the speed of reaction wheel #1 or reaction wheel #2 exceeds this value, the data quality flag is set." ; 
		reaction_wheel_speed_threshold:units = "revolutions per minute (RPM)" ; 
	double expected_pixel_ratio (range) ; 
		expected_pixel_ratio:long_name = "expected_pixel_ratio" ; 
		expected_pixel_ratio:comments = "The range within which the pixel ratio should be, otherwise a quality flag is set." ; 
		expected_pixel_ratio:units = "unitless" ; 
	double contam_min_ion_count_rate (scalar) ; 
		contam_min_ion_count_rate:long_name = "contam_min_ion_count_rate" ; 
		contam_min_ion_count_rate:comments = "For electron contamination assessment: minimum ion count rate to check for electrons in the ion data." ; 
		contam_min_ion_count_rate:units = "#/s" ; 
	double contam_min_ion_energy (scalar) ; 
		contam_min_ion_energy:long_name = "contam_min_ion_energy" ; 
		contam_min_ion_energy:comments = "For electron contamination assessment: energy for minimum ion count rate." ; 
		contam_min_ion_energy:units = "keV" ; 
	double contam_min_electron_count_rate (scalar) ; 
		contam_min_electron_count_rate:long_name = "contam_min_electron_count_rate" ; 
		contam_min_electron_count_rate:comments = "For electron contamination assessment: minimum electron count rate to check for electrons in the ion data." ; 
		contam_min_electron_count_rate:units = "#/s" ; 
	double contam_min_electron_energy (scalar) ; 
		contam_min_electron_energy:long_name = "contam_min_electron_energy" ; 
		contam_min_electron_energy:comments = "For electron contamination assessment: energy for minimum electron count rate." ; 
		contam_min_electron_energy:units = "keV" ; 
	double contam_min_ion_ratio (scalar) ; 
		contam_min_ion_ratio:long_name = "contam_min_ion_ratio" ; 
		contam_min_ion_ratio:comments = "For electron contamination assessment: minimum ratio (O/(O+F)) to assess contam risk." ; 
		contam_min_ion_ratio:units = "#/s" ; 
	double contam_min_ion_ratio_energy (scalar) ; 
		contam_min_ion_ratio_energy:long_name = "contam_min_ion_ratio_energy" ; 
		contam_min_ion_ratio_energy:comments = "For electron contamination assessment: energy for minimum ion ratio calculation." ; 
		contam_min_ion_ratio_energy:units = "keV" ; 
	double contam_ion_max_deviation_power_law (scalar) ; 
		contam_ion_max_deviation_power_law:long_name = "contam_ion_max_deviation_power_law" ; 
		contam_ion_max_deviation_power_law:comments = "For electron contamination assessment: if ion fluxes eval'ed at end points, max difference of line between those and the data." ; 
		contam_ion_max_deviation_power_law:units = "unitless" ; 
	double contam_ion_energy_range (range) ; 
		contam_ion_energy_range:long_name = "contam_ion_energy_range" ; 
		contam_ion_energy_range:comments = "For electron contamination assessment: range of energies in ion data affected by electron contamination." ; 
		contam_ion_energy_range:units = "keV" ; 
	uint64 pulser_on_qflag_index (detectors) ; 
		pulser_on_qflag_index:long_name = "pulser_on_qflag_index" ; 
		pulser_on_qflag_index:comments = "Bit indices of pulser enabled quality flags " ; 
		pulser_on_qflag_index:units = "unitless" ; 
	uint64 high_noise_sigma_qflag_index (detectors) ; 
		high_noise_sigma_qflag_index:long_name = "high_noise_sigma_qflag_index" ; 
		high_noise_sigma_qflag_index:comments = "Bit indices of noise sigma quality flags" ; 
		high_noise_sigma_qflag_index:units = "unitless" ; 
	uint64 any_detector_disabled_qflag_index (scalar) ; 
		any_detector_disabled_qflag_index:long_name = "any_detector_disabled_qflag_index" ; 
		any_detector_disabled_qflag_index:comments = "Bit indices of detector disabled quality flags" ; 
		any_detector_disabled_qflag_index:units = "unitless" ; 
	uint64 decimation_qflag_index (channels_decimated) ; 
		decimation_qflag_index:long_name = "decimation_qflag_index" ; 
		decimation_qflag_index:comments = "Bit indices of decimation active quality flags" ; 
		decimation_qflag_index:units = "unitless" ; 
	uint64 high_rate_qflag_index (detectors) ; 
		high_rate_qflag_index:long_name = "high_rate_qflag_index" ; 
		high_rate_qflag_index:comments = "Bit indices of high housekeeping rates flags" ; 
		high_rate_qflag_index:units = "unitless" ; 
	uint64 extreme_temperature_qflag_index (scalar) ; 
		extreme_temperature_qflag_index:long_name = "extreme_temperature_qflag_index" ; 
		extreme_temperature_qflag_index:comments = "Bit indices of temperature quality flags" ; 
		extreme_temperature_qflag_index:units = "unitless" ; 
	uint64 nonstandard_config_qflag_index (scalar) ; 
		nonstandard_config_qflag_index:long_name = "nonstandard_config_qflag_index" ; 
		nonstandard_config_qflag_index:comments = "Bit indices of non-standard configuration quality flags" ; 
		nonstandard_config_qflag_index:units = "unitless" ; 
	uint64 high_reaction_wheel_speed_qflag_index (reaction_wheels) ; 
		high_reaction_wheel_speed_qflag_index:long_name = "high_reaction_wheel_speed_qflag_index" ; 
		high_reaction_wheel_speed_qflag_index:comments = "Bit indices of reaction wheel speed quality flags" ; 
		high_reaction_wheel_speed_qflag_index:units = "unitless" ; 
	uint64 bad_iru_qflag_index (scalar) ; 
		bad_iru_qflag_index:long_name = "bad_iru_qflag_index" ; 
		bad_iru_qflag_index:comments = "Bit index of bad IRU in quality flag" ; 
		bad_iru_qflag_index:units = "unitless" ; 
	uint64 swfo_offpointing_qflag_index (scalar) ; 
		swfo_offpointing_qflag_index:long_name = "swfo_offpointing_qflag_index" ; 
		swfo_offpointing_qflag_index:comments = "Bit index of SWFO offpointing in quality flag." ; 
		swfo_offpointing_qflag_index:units = "unitless" ; 
	uint64 sun_in_stis_fov_qflag_index (scalar) ; 
		sun_in_stis_fov_qflag_index:long_name = "sun_in_stis_fov_qflag_index" ; 
		sun_in_stis_fov_qflag_index:comments = "Bit index of sun-in-STIS-FOV in quality flag." ; 
		sun_in_stis_fov_qflag_index:units = "unitless" ; 
	uint64 bad_elec_pixel_merge_qflag_index (range) ; 
		bad_elec_pixel_merge_qflag_index:long_name = "bad_elec_pixel_merge_qflag_index" ; 
		bad_elec_pixel_merge_qflag_index:comments = "Bit indices of suspicious pixel merging for electron data in quality flag." ; 
		bad_elec_pixel_merge_qflag_index:units = "unitless" ; 
	uint64 bad_ion_pixel_merge_qflag_index (range) ; 
		bad_ion_pixel_merge_qflag_index:long_name = "bad_ion_pixel_merge_qflag_index" ; 
		bad_ion_pixel_merge_qflag_index:comments = "Bit indices of suspicious pixel merging for ion data in quality flag." ; 
		bad_ion_pixel_merge_qflag_index:units = "unitless" ; 
	uint64 elec_contam_qflag_index (scalar) ; 
		elec_contam_qflag_index:long_name = "elec_contam_qflag_index" ; 
		elec_contam_qflag_index:comments = "Bit index of electron contamination indicator in quality flag." ; 
		elec_contam_qflag_index:units = "unitless" ; 
	double epam_electron_edge_energies (epam_electron_edge_energies) ; 
		epam_electron_edge_energies:long_name = "epam_electron_edge_energies" ; 
		epam_electron_edge_energies:comments = "Edge energies of each EPAM LEFS60 electron channel (except the highest energy, which is from the deflected electron spectrometer)" ; 
		epam_electron_edge_energies:units = "keV" ; 
	double epam_ion_edge_energies (epam_ion_edge_energies) ; 
		epam_ion_edge_energies:long_name = "epam_ion_edge_energies" ; 
		epam_ion_edge_energies:comments = "Edge energies of each EPAM LEMS120 ion channel" ; 
		epam_ion_edge_energies:units = "keV" ; 
	double maximum_swfo_sun_offpointing_angle (scalar) ; 
		maximum_swfo_sun_offpointing_angle:long_name = "maximum_swfo_sun_offpointing_angle" ; 
		maximum_swfo_sun_offpointing_angle:comments = "If the angle between SWFO's nominal sun-pointing direction (the x-component in spacecraft coordinates) and the sun exceeds this value, set a quality flag." ; 
		maximum_swfo_sun_offpointing_angle:units = "degrees" ; 
	double minimum_stis_sun_angle (scalar) ; 
		minimum_stis_sun_angle:long_name = "minimum_stis_sun_angle" ; 
		minimum_stis_sun_angle:comments = "If the angle between the center of STIS's field-of-view and the sun is below this value, set a quality flag." ; 
		minimum_stis_sun_angle:units = "degrees" ; 
	double stis_boresight_sc_unit_vector (dim_unit_vector) ; 
		stis_boresight_sc_unit_vector:long_name = "stis_boresight_sc_unit_vector" ; 
		stis_boresight_sc_unit_vector:comments = "The 3-element unit vector of the centroid of STIS's field-of-view in spacecraft coordinates (where X points along the coronagraph and solar panel)." ; 
		stis_boresight_sc_unit_vector:units = "unitless" ; 
// global attributes:
	:Conventions = "ACDD-1.3, Spase v2.2.6" ;
	:title = "undefined" ;
	:id = " " ; 
	:summary = "undefined" ;
	:keywords = "undefined" ;
	:keywords_vocabulary = "SPASE: Space Physics Archive Search and Extract Data Model version 2.2.6, GCMD: NASA Global Change Master Directory (GCMD) Earth Science Keywords version 8.5" ;
	:naming_authority = "gov.nesdis.noaa" ;
	:history = "See algorithm information." ;
	:source = "undefined" ;
	:processing_level = "undefined" ;
	:processing_level_description = "undefined" ;
	:license = "These data may be redistributed and used without restriction. " ;
	:acknowledgment = "undefined" ;
	:metadata_link = "undefined" ;
	:date_created = " " ; 
	:creator_name = "undefined" ;
	:creator_type = "undefined" ;
	:creator_institution = "DOC/NOAA/NCEI/COGS/GSB/STP" ;
	:creator_email = "undefined" ;
	:creator_url = "https://www.ncei.noaa.gov/" ;
	:institution = "DOC/NOAA/NESDIS> U.S. Department of Commerce, National Oceanic and Atmospheric Administration, National Environmental Satellite, Data, and Information Services" ;
	:publisher_name = "National Centers for Environmental Information" ;
	:publisher_type = "institution" ;
	:publisher_institution = "DOC/NOAA/NESDIS/NCEI" ;
	:publisher_email = "ncei.info@noaa.gov" ;
	:publisher_url = "https://www.ncei.noaa.gov/" ;
	:references = "undefined" ;
	:instrument = "undefined" ;
	:instrument_id = " " ; 
	:orbital_slot = " " ; 
	:program = "undefined" ;
	:project = "undefined" ;
	:platform = " " ; 
	:NWS_system_environment = " " ; 
	:NWS_production_site = " " ; 
	:comment = "undefined" ;
	:comment_2 = "undefined" ;
	:time_coverage_start = " " ; 
	:time_coverage_end = " " ; 
	:time_coverage_resolution = "undefined" ;
	:processing_parameters_file = " " ; 
	:algorithm = "undefined" ;
	:algorithm_version = " " ; 
	:algorithm_date = " " ; 
	:_Format = "netCDF-4" ;
	:algorithm_parameters = "None" ;
	:input_system_environments = " " ; 
	:input_files_first = " " ; 
	:input_files_last = " " ; 
	:input_files_total = " " ; 
	:LUT_filename = " " ; 
}