  <cdf_var
      name   = "dfb_xspec_src1"
      type   = "integer"      
      string = "true"
      string_len = "8">
  <cdf_att
        FIELDNAM = "xspec_src1"
        FORMAT = "I08"
        LABLAXIS = "xspec_src1"
        VAR_TYPE = "data"
        DATA_TYPE = "CDF_INT2"
        FILLVAL = "-32767"
        DISPLAY_TYPE = "time_series"
        VALIDMIN = "0"
        VALIDMAX = "3"
        SCALEMIN = "0"
        SCALEMAX = "3"
        UNITS = "None"
        CATDESC = "Source select Spectrum 1"
        DEPEND_0 = "epoch">
    </cdf_att>
  </cdf_var>
